GET http://localhost:3000/api/products

###

POST http://localhost:3000/api/products
content-type: application/json

{
    "name": "„Coca-Cola“ (355 ml)",
    "type": "Gėrimas",
    "price": 1.5
}

###

PATCH http://localhost:3000/api/products/6390eb1ddf9e1052c0803544
content-type: application/json

{
    "image": "kebab"
}

###

DELETE http://localhost:3000/api/products/6390e68a8a0ed484b2951e37
