GET http://localhost:3000/products

###

POST http://localhost:3000/products
content-type: application/json

{
    "name": "„Coca-Cola“ (355 ml)",
    "type": "Gėrimas",
    "price": 1.5
}

###

PATCH http://localhost:3000/products/6390f02ea007689bcc125b6e
content-type: application/json

{
    "name": "„Coca-Cola“ (355 ml)"
}

###

DELETE http://localhost:3000/products/6390e68a8a0ed484b2951e37
