### "REST Client" extention

GET http://localhost:3000/api/products

###

POST http://localhost:3000/api/products
content-type: application/json

{
    "name": "„Coca-Cola“ (0,33 l)",
    "type": "Gėrimas",
    "price": 1.5
}

###

GET http://localhost:3000/api/orders/000000000000000000000000

###

POST http://localhost:3000/api/products
content-type: application/json

{
    "name": "Negazuotas vanduo „Neptūnas“ (0,5 l)",
    "type": "Gėrimas",
    "price": 1,
    "image": "water",
    "stock": 0
}

###

PATCH http://localhost:3000/api/products/6390f02ea007689bcc125b6e
content-type: application/json

{
    "name": "„Coca-Cola“ (0,33 l)"
}

###

DELETE http://localhost:3000/api/products/639f72d8211f94a7515c5f50
